#!/bin/bash

g++ -g -o cbot main.cpp Chameleon.cpp ConfigFile.cpp gcParser.cpp motion_planner.cpp VC0706.cpp calibrate.cpp -lboost_regex -lpthread -lboost_system -lopencv_core -lopencv_imgproc -lopencv_highgui  -std=c++11
